# Generated by Django 3.1.5 on 2022-12-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
